name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees activar el pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push PHP 8.2 image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -f ./php8.2/Dockerfile --pull -t ghcr.io/bytech-ar/laravel-docker:php82 --push .

      - name: Build and push PHP 8.4 image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -f ./php8.4/Dockerfile --pull -t ghcr.io/bytech-ar/laravel-docker:php84 --push .